feat: Added user routes, linting and containerization
Added lint configuration.
Added containerization using docker and docker compose.
Added tests for login and me route

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,10 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npx lint-staged
+if npm run lint && make test;
+then
+    exit 0
+else
+    echo "\\e[1;33m One or more tests are failing; please fix those tests before commiting"
+    exit 1
+fi
